### PR TITLE
Force removal of conflicting bundle command

### PR DESCRIPTION
**Pull request by josemotanet**
See this: https://github.com/rubygems/rubygems/issues/2058#issuecomment-342326819

### CODE REVIEW

**Comment by thisismydesign** [comment]
Sorry to barge in on you, but you can also do `gem install bundler --force` which is probably nicer. :)

**Comment by josemotanet** [comment]
Thanks @thisismydesign, I'll make sure to test it as well.

**Comment by josemotanet** [comment]
@mattridenour-goodguide can you review this please? Might help out with the issue at hand. Thanks.

**Comment by mattridenour-goodguide** [comment]
@josemotanet ~LGTM.  In theory, I think I prefer your initial approach because it solves the specific problem and won't have possible unintended consequences down the road by disabling dependency checking.  (Of the successfully building a broken image kind.) But, since its bundler, if something goes wrong, it will certainly throw an error when bundling in a child image.

**Pull request merged**
